'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

' Original file name:
' Generation date: 02.10.2012 11:11:56

Imports Microsoft.VisualBasic
Imports System
Namespace ODataV3Example.Northwind

	''' <summary>
	''' There are no comments for XpoExampleContext in the schema.
	''' </summary>
	Partial Public Class XpoExampleContext
		Inherits System.Data.Services.Client.DataServiceContext
		''' <summary>
		''' Initialize a new XpoExampleContext object.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Sub New(ByVal serviceRoot As Global.System.Uri)
			MyBase.New(serviceRoot, Global.System.Data.Services.Common.DataServiceProtocolVersion.V3)
			Me.ResolveName = New Global.System.Func(Of Global.System.Type, String)(AddressOf Me.ResolveNameFromType)
			Me.ResolveType = New Global.System.Func(Of String, Global.System.Type)(AddressOf Me.ResolveTypeFromName)
			Me.OnContextCreated()
		End Sub
		Partial Private Sub OnContextCreated()
		End Sub
		''' <summary>
		''' Since the namespace configured for this service reference
		''' in Visual Studio is different from the one indicated in the
		''' server schema, use type-mappers to map between the two.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
			If typeName.StartsWith("Northwind", Global.System.StringComparison.Ordinal) Then
				Return Me.GetType().Assembly.GetType(String.Concat("ODataV3Example.Northwind", typeName.Substring(9)), False)
			End If
			Return Nothing
		End Function
		''' <summary>
		''' Since the namespace configured for this service reference
		''' in Visual Studio is different from the one indicated in the
		''' server schema, use type-mappers to map between the two.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
			If clientType.Namespace.Equals("ODataV3Example.Northwind", Global.System.StringComparison.Ordinal) Then
				Return String.Concat("Northwind.", clientType.Name)
			End If
			Return Nothing
		End Function
		''' <summary>
		''' There are no comments for Customers in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public ReadOnly Property Customers() As Global.System.Data.Services.Client.DataServiceQuery(Of Customers)
			Get
				If (Me._Customers Is Nothing) Then
					Me._Customers = MyBase.CreateQuery(Of Customers)("Customers")
				End If
				Return Me._Customers
			End Get
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Customers As Global.System.Data.Services.Client.DataServiceQuery(Of Customers)
		''' <summary>
		''' There are no comments for Products in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public ReadOnly Property Products() As Global.System.Data.Services.Client.DataServiceQuery(Of Products)
			Get
				If (Me._Products Is Nothing) Then
					Me._Products = MyBase.CreateQuery(Of Products)("Products")
				End If
				Return Me._Products
			End Get
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Products As Global.System.Data.Services.Client.DataServiceQuery(Of Products)
		''' <summary>
		''' There are no comments for Categories in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public ReadOnly Property Categories() As Global.System.Data.Services.Client.DataServiceQuery(Of Categories)
			Get
				If (Me._Categories Is Nothing) Then
					Me._Categories = MyBase.CreateQuery(Of Categories)("Categories")
				End If
				Return Me._Categories
			End Get
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Categories As Global.System.Data.Services.Client.DataServiceQuery(Of Categories)
		''' <summary>
		''' There are no comments for Employees in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public ReadOnly Property Employees() As Global.System.Data.Services.Client.DataServiceQuery(Of Employees)
			Get
				If (Me._Employees Is Nothing) Then
					Me._Employees = MyBase.CreateQuery(Of Employees)("Employees")
				End If
				Return Me._Employees
			End Get
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Employees As Global.System.Data.Services.Client.DataServiceQuery(Of Employees)
		''' <summary>
		''' There are no comments for Shippers in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public ReadOnly Property Shippers() As Global.System.Data.Services.Client.DataServiceQuery(Of Shippers)
			Get
				If (Me._Shippers Is Nothing) Then
					Me._Shippers = MyBase.CreateQuery(Of Shippers)("Shippers")
				End If
				Return Me._Shippers
			End Get
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Shippers As Global.System.Data.Services.Client.DataServiceQuery(Of Shippers)
		''' <summary>
		''' There are no comments for Orders in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public ReadOnly Property Orders() As Global.System.Data.Services.Client.DataServiceQuery(Of Orders)
			Get
				If (Me._Orders Is Nothing) Then
					Me._Orders = MyBase.CreateQuery(Of Orders)("Orders")
				End If
				Return Me._Orders
			End Get
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Orders As Global.System.Data.Services.Client.DataServiceQuery(Of Orders)
		''' <summary>
		''' There are no comments for Suppliers in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public ReadOnly Property Suppliers() As Global.System.Data.Services.Client.DataServiceQuery(Of Suppliers)
			Get
				If (Me._Suppliers Is Nothing) Then
					Me._Suppliers = MyBase.CreateQuery(Of Suppliers)("Suppliers")
				End If
				Return Me._Suppliers
			End Get
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Suppliers As Global.System.Data.Services.Client.DataServiceQuery(Of Suppliers)
		''' <summary>
		''' There are no comments for Customers in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Sub AddToCustomers(ByVal customers As Customers)
			MyBase.AddObject("Customers", customers)
		End Sub
		''' <summary>
		''' There are no comments for Products in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Sub AddToProducts(ByVal products As Products)
			MyBase.AddObject("Products", products)
		End Sub
		''' <summary>
		''' There are no comments for Categories in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Sub AddToCategories(ByVal categories As Categories)
			MyBase.AddObject("Categories", categories)
		End Sub
		''' <summary>
		''' There are no comments for Employees in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Sub AddToEmployees(ByVal employees As Employees)
			MyBase.AddObject("Employees", employees)
		End Sub
		''' <summary>
		''' There are no comments for Shippers in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Sub AddToShippers(ByVal shippers As Shippers)
			MyBase.AddObject("Shippers", shippers)
		End Sub
		''' <summary>
		''' There are no comments for Orders in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Sub AddToOrders(ByVal orders As Orders)
			MyBase.AddObject("Orders", orders)
		End Sub
		''' <summary>
		''' There are no comments for Suppliers in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Sub AddToSuppliers(ByVal suppliers As Suppliers)
			MyBase.AddObject("Suppliers", suppliers)
		End Sub
	End Class
	''' <summary>
	''' There are no comments for Northwind.Customers in the schema.
	''' </summary>
	''' <KeyProperties>
	''' CustomerID
	''' </KeyProperties>
	<Global.System.Data.Services.Common.EntitySetAttribute("Customers"), Global.System.Data.Services.Common.DataServiceKeyAttribute("CustomerID")> _
	Partial Public Class Customers
		Implements System.ComponentModel.INotifyPropertyChanged
		''' <summary>
		''' Create a new Customers object.
		''' </summary>
		''' <param name="customerID">Initial value of CustomerID.</param>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Shared Function CreateCustomers(ByVal customerID As String) As Customers
			Dim customers As New Customers()
			customers.CustomerID = customerID
			Return customers
		End Function
		''' <summary>
		''' There are no comments for Property Address in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Address() As String
			Get
				Return Me._Address
			End Get
			Set(ByVal value As String)
				Me.OnAddressChanging(value)
				Me._Address = value
				Me.OnAddressChanged()
				Me.OnPropertyChanged("Address")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Address As String
		Partial Private Sub OnAddressChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnAddressChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property City in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property City() As String
			Get
				Return Me._City
			End Get
			Set(ByVal value As String)
				Me.OnCityChanging(value)
				Me._City = value
				Me.OnCityChanged()
				Me.OnPropertyChanged("City")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _City As String
		Partial Private Sub OnCityChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCityChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property CompanyName in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property CompanyName() As String
			Get
				Return Me._CompanyName
			End Get
			Set(ByVal value As String)
				Me.OnCompanyNameChanging(value)
				Me._CompanyName = value
				Me.OnCompanyNameChanged()
				Me.OnPropertyChanged("CompanyName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _CompanyName As String
		Partial Private Sub OnCompanyNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCompanyNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ContactName in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ContactName() As String
			Get
				Return Me._ContactName
			End Get
			Set(ByVal value As String)
				Me.OnContactNameChanging(value)
				Me._ContactName = value
				Me.OnContactNameChanged()
				Me.OnPropertyChanged("ContactName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ContactName As String
		Partial Private Sub OnContactNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnContactNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ContactTitle in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ContactTitle() As String
			Get
				Return Me._ContactTitle
			End Get
			Set(ByVal value As String)
				Me.OnContactTitleChanging(value)
				Me._ContactTitle = value
				Me.OnContactTitleChanged()
				Me.OnPropertyChanged("ContactTitle")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ContactTitle As String
		Partial Private Sub OnContactTitleChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnContactTitleChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Country in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Country() As String
			Get
				Return Me._Country
			End Get
			Set(ByVal value As String)
				Me.OnCountryChanging(value)
				Me._Country = value
				Me.OnCountryChanged()
				Me.OnPropertyChanged("Country")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Country As String
		Partial Private Sub OnCountryChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCountryChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property CustomerID in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property CustomerID() As String
			Get
				Return Me._CustomerID
			End Get
			Set(ByVal value As String)
				Me.OnCustomerIDChanging(value)
				Me._CustomerID = value
				Me.OnCustomerIDChanged()
				Me.OnPropertyChanged("CustomerID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _CustomerID As String
		Partial Private Sub OnCustomerIDChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCustomerIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Fax in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Fax() As String
			Get
				Return Me._Fax
			End Get
			Set(ByVal value As String)
				Me.OnFaxChanging(value)
				Me._Fax = value
				Me.OnFaxChanged()
				Me.OnPropertyChanged("Fax")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Fax As String
		Partial Private Sub OnFaxChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnFaxChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Phone in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Phone() As String
			Get
				Return Me._Phone
			End Get
			Set(ByVal value As String)
				Me.OnPhoneChanging(value)
				Me._Phone = value
				Me.OnPhoneChanged()
				Me.OnPropertyChanged("Phone")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Phone As String
		Partial Private Sub OnPhoneChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnPhoneChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property PostalCode in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property PostalCode() As String
			Get
				Return Me._PostalCode
			End Get
			Set(ByVal value As String)
				Me.OnPostalCodeChanging(value)
				Me._PostalCode = value
				Me.OnPostalCodeChanged()
				Me.OnPropertyChanged("PostalCode")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _PostalCode As String
		Partial Private Sub OnPostalCodeChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnPostalCodeChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Region in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Region() As String
			Get
				Return Me._Region
			End Get
			Set(ByVal value As String)
				Me.OnRegionChanging(value)
				Me._Region = value
				Me.OnRegionChanged()
				Me.OnPropertyChanged("Region")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Region As String
		Partial Private Sub OnRegionChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnRegionChanged()
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
			If (Me.PropertyChangedEvent IsNot Nothing) Then
				RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
			End If
		End Sub
	End Class
	''' <summary>
	''' There are no comments for Northwind.Products in the schema.
	''' </summary>
	''' <KeyProperties>
	''' ProductID
	''' </KeyProperties>
	<Global.System.Data.Services.Common.EntitySetAttribute("Products"), Global.System.Data.Services.Common.DataServiceKeyAttribute("ProductID")> _
	Partial Public Class Products
		Implements System.ComponentModel.INotifyPropertyChanged
		''' <summary>
		''' Create a new Products object.
		''' </summary>
		''' <param name="productID">Initial value of ProductID.</param>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Shared Function CreateProducts(ByVal productID As Integer) As Products
			Dim products As New Products()
			products.ProductID = productID
			Return products
		End Function
		''' <summary>
		''' There are no comments for Property Discontinued in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Discontinued() As Boolean?
			Get
				Return Me._Discontinued
			End Get
			Set(ByVal value? As Boolean)
				Me.OnDiscontinuedChanging(value)
				Me._Discontinued = value
				Me.OnDiscontinuedChanged()
				Me.OnPropertyChanged("Discontinued")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Discontinued? As Boolean
		Partial Private Sub OnDiscontinuedChanging(ByVal value? As Boolean)
		End Sub
		Partial Private Sub OnDiscontinuedChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property EAN13 in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property EAN13() As String
			Get
				Return Me._EAN13
			End Get
			Set(ByVal value As String)
				Me.OnEAN13Changing(value)
				Me._EAN13 = value
				Me.OnEAN13Changed()
				Me.OnPropertyChanged("EAN13")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _EAN13 As String
		Partial Private Sub OnEAN13Changing(ByVal value As String)
		End Sub
		Partial Private Sub OnEAN13Changed()
		End Sub
		''' <summary>
		''' There are no comments for Property ProductID in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ProductID() As Integer
			Get
				Return Me._ProductID
			End Get
			Set(ByVal value As Integer)
				Me.OnProductIDChanging(value)
				Me._ProductID = value
				Me.OnProductIDChanged()
				Me.OnPropertyChanged("ProductID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ProductID As Integer
		Partial Private Sub OnProductIDChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnProductIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ProductName in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ProductName() As String
			Get
				Return Me._ProductName
			End Get
			Set(ByVal value As String)
				Me.OnProductNameChanging(value)
				Me._ProductName = value
				Me.OnProductNameChanged()
				Me.OnPropertyChanged("ProductName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ProductName As String
		Partial Private Sub OnProductNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnProductNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property QuantityPerUnit in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property QuantityPerUnit() As String
			Get
				Return Me._QuantityPerUnit
			End Get
			Set(ByVal value As String)
				Me.OnQuantityPerUnitChanging(value)
				Me._QuantityPerUnit = value
				Me.OnQuantityPerUnitChanged()
				Me.OnPropertyChanged("QuantityPerUnit")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _QuantityPerUnit As String
		Partial Private Sub OnQuantityPerUnitChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnQuantityPerUnitChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ReorderLevel in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ReorderLevel() As Short?
			Get
				Return Me._ReorderLevel
			End Get
			Set(ByVal value? As Short)
				Me.OnReorderLevelChanging(value)
				Me._ReorderLevel = value
				Me.OnReorderLevelChanged()
				Me.OnPropertyChanged("ReorderLevel")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ReorderLevel? As Short
		Partial Private Sub OnReorderLevelChanging(ByVal value? As Short)
		End Sub
		Partial Private Sub OnReorderLevelChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property UnitPrice in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property UnitPrice() As Decimal?
			Get
				Return Me._UnitPrice
			End Get
			Set(ByVal value? As Decimal)
				Me.OnUnitPriceChanging(value)
				Me._UnitPrice = value
				Me.OnUnitPriceChanged()
				Me.OnPropertyChanged("UnitPrice")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _UnitPrice? As Decimal
		Partial Private Sub OnUnitPriceChanging(ByVal value? As Decimal)
		End Sub
		Partial Private Sub OnUnitPriceChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property UnitsInStock in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property UnitsInStock() As Short?
			Get
				Return Me._UnitsInStock
			End Get
			Set(ByVal value? As Short)
				Me.OnUnitsInStockChanging(value)
				Me._UnitsInStock = value
				Me.OnUnitsInStockChanged()
				Me.OnPropertyChanged("UnitsInStock")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _UnitsInStock? As Short
		Partial Private Sub OnUnitsInStockChanging(ByVal value? As Short)
		End Sub
		Partial Private Sub OnUnitsInStockChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property UnitsOnOrder in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property UnitsOnOrder() As Short?
			Get
				Return Me._UnitsOnOrder
			End Get
			Set(ByVal value? As Short)
				Me.OnUnitsOnOrderChanging(value)
				Me._UnitsOnOrder = value
				Me.OnUnitsOnOrderChanged()
				Me.OnPropertyChanged("UnitsOnOrder")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _UnitsOnOrder? As Short
		Partial Private Sub OnUnitsOnOrderChanging(ByVal value? As Short)
		End Sub
		Partial Private Sub OnUnitsOnOrderChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ExtendedPrice in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ExtendedPrice() As Decimal?
			Get
				Return Me._ExtendedPrice
			End Get
			Set(ByVal value? As Decimal)
				Me.OnExtendedPriceChanging(value)
				Me._ExtendedPrice = value
				Me.OnExtendedPriceChanged()
				Me.OnPropertyChanged("ExtendedPrice")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ExtendedPrice? As Decimal
		Partial Private Sub OnExtendedPriceChanging(ByVal value? As Decimal)
		End Sub
		Partial Private Sub OnExtendedPriceChanged()
		End Sub
		''' <summary>
		''' There are no comments for CategoryID in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property CategoryID() As Categories
			Get
				Return Me._CategoryID
			End Get
			Set(ByVal value As Categories)
				Me._CategoryID = value
				Me.OnPropertyChanged("CategoryID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _CategoryID As Categories
		''' <summary>
		''' There are no comments for SupplierID in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property SupplierID() As Suppliers
			Get
				Return Me._SupplierID
			End Get
			Set(ByVal value As Suppliers)
				Me._SupplierID = value
				Me.OnPropertyChanged("SupplierID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _SupplierID As Suppliers
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
			If (Me.PropertyChangedEvent IsNot Nothing) Then
				RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
			End If
		End Sub
	End Class
	''' <summary>
	''' There are no comments for Northwind.Categories in the schema.
	''' </summary>
	''' <KeyProperties>
	''' CategoryID
	''' </KeyProperties>
	<Global.System.Data.Services.Common.EntitySetAttribute("Categories"), Global.System.Data.Services.Common.DataServiceKeyAttribute("CategoryID")> _
	Partial Public Class Categories
		Implements System.ComponentModel.INotifyPropertyChanged
		''' <summary>
		''' Create a new Categories object.
		''' </summary>
		''' <param name="categoryID">Initial value of CategoryID.</param>
		''' <param name="streamPicture">Initial value of StreamPicture.</param>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Shared Function CreateCategories(ByVal categoryID As Integer, ByVal streamPicture As Global.System.Data.Services.Client.DataServiceStreamLink) As Categories
			Dim categories As New Categories()
			categories.CategoryID = categoryID
			categories.StreamPicture = streamPicture
			Return categories
		End Function
		''' <summary>
		''' There are no comments for Property CategoryID in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property CategoryID() As Integer
			Get
				Return Me._CategoryID
			End Get
			Set(ByVal value As Integer)
				Me.OnCategoryIDChanging(value)
				Me._CategoryID = value
				Me.OnCategoryIDChanged()
				Me.OnPropertyChanged("CategoryID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _CategoryID As Integer
		Partial Private Sub OnCategoryIDChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnCategoryIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property CategoryName in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property CategoryName() As String
			Get
				Return Me._CategoryName
			End Get
			Set(ByVal value As String)
				Me.OnCategoryNameChanging(value)
				Me._CategoryName = value
				Me.OnCategoryNameChanged()
				Me.OnPropertyChanged("CategoryName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _CategoryName As String
		Partial Private Sub OnCategoryNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCategoryNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Description in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Description() As String
			Get
				Return Me._Description
			End Get
			Set(ByVal value As String)
				Me.OnDescriptionChanging(value)
				Me._Description = value
				Me.OnDescriptionChanged()
				Me.OnPropertyChanged("Description")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Description As String
		Partial Private Sub OnDescriptionChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnDescriptionChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property StreamPicture in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property StreamPicture() As Global.System.Data.Services.Client.DataServiceStreamLink
			Get
				Return Me._StreamPicture
			End Get
			Set(ByVal value As System.Data.Services.Client.DataServiceStreamLink)
				Me.OnStreamPictureChanging(value)
				Me._StreamPicture = value
				Me.OnStreamPictureChanged()
				Me.OnPropertyChanged("StreamPicture")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _StreamPicture As Global.System.Data.Services.Client.DataServiceStreamLink
		Partial Private Sub OnStreamPictureChanging(ByVal value As Global.System.Data.Services.Client.DataServiceStreamLink)
		End Sub
		Partial Private Sub OnStreamPictureChanged()
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
			If (Me.PropertyChangedEvent IsNot Nothing) Then
				RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
			End If
		End Sub
	End Class
	''' <summary>
	''' There are no comments for Northwind.Employees in the schema.
	''' </summary>
	''' <KeyProperties>
	''' EmployeeID
	''' </KeyProperties>
	<Global.System.Data.Services.Common.EntitySetAttribute("Employees"), Global.System.Data.Services.Common.DataServiceKeyAttribute("EmployeeID")> _
	Partial Public Class Employees
		Implements System.ComponentModel.INotifyPropertyChanged
		''' <summary>
		''' Create a new Employees object.
		''' </summary>
		''' <param name="employeeID">Initial value of EmployeeID.</param>
		''' <param name="photo">Initial value of Photo.</param>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Shared Function CreateEmployees(ByVal employeeID As Integer, ByVal photo As Global.System.Data.Services.Client.DataServiceStreamLink) As Employees
			Dim employees As New Employees()
			employees.EmployeeID = employeeID
			employees.Photo = photo
			Return employees
		End Function
		''' <summary>
		''' There are no comments for Property Address in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Address() As String
			Get
				Return Me._Address
			End Get
			Set(ByVal value As String)
				Me.OnAddressChanging(value)
				Me._Address = value
				Me.OnAddressChanged()
				Me.OnPropertyChanged("Address")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Address As String
		Partial Private Sub OnAddressChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnAddressChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property BirthDate in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property BirthDate() As Global.System.DateTime?
			Get
				Return Me._BirthDate
			End Get
			Set(ByVal value? As System.DateTime)
				Me.OnBirthDateChanging(value)
				Me._BirthDate = value
				Me.OnBirthDateChanged()
				Me.OnPropertyChanged("BirthDate")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _BirthDate? As Global.System.DateTime
		Partial Private Sub OnBirthDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnBirthDateChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property City in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property City() As String
			Get
				Return Me._City
			End Get
			Set(ByVal value As String)
				Me.OnCityChanging(value)
				Me._City = value
				Me.OnCityChanged()
				Me.OnPropertyChanged("City")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _City As String
		Partial Private Sub OnCityChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCityChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Country in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Country() As String
			Get
				Return Me._Country
			End Get
			Set(ByVal value As String)
				Me.OnCountryChanging(value)
				Me._Country = value
				Me.OnCountryChanged()
				Me.OnPropertyChanged("Country")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Country As String
		Partial Private Sub OnCountryChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCountryChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property EmployeeID in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property EmployeeID() As Integer
			Get
				Return Me._EmployeeID
			End Get
			Set(ByVal value As Integer)
				Me.OnEmployeeIDChanging(value)
				Me._EmployeeID = value
				Me.OnEmployeeIDChanged()
				Me.OnPropertyChanged("EmployeeID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _EmployeeID As Integer
		Partial Private Sub OnEmployeeIDChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnEmployeeIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Extension in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Extension() As String
			Get
				Return Me._Extension
			End Get
			Set(ByVal value As String)
				Me.OnExtensionChanging(value)
				Me._Extension = value
				Me.OnExtensionChanged()
				Me.OnPropertyChanged("Extension")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Extension As String
		Partial Private Sub OnExtensionChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnExtensionChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property FirstName in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property FirstName() As String
			Get
				Return Me._FirstName
			End Get
			Set(ByVal value As String)
				Me.OnFirstNameChanging(value)
				Me._FirstName = value
				Me.OnFirstNameChanged()
				Me.OnPropertyChanged("FirstName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _FirstName As String
		Partial Private Sub OnFirstNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnFirstNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property HireDate in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property HireDate() As Global.System.DateTime?
			Get
				Return Me._HireDate
			End Get
			Set(ByVal value? As System.DateTime)
				Me.OnHireDateChanging(value)
				Me._HireDate = value
				Me.OnHireDateChanged()
				Me.OnPropertyChanged("HireDate")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _HireDate? As Global.System.DateTime
		Partial Private Sub OnHireDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnHireDateChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property HomePhone in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property HomePhone() As String
			Get
				Return Me._HomePhone
			End Get
			Set(ByVal value As String)
				Me.OnHomePhoneChanging(value)
				Me._HomePhone = value
				Me.OnHomePhoneChanged()
				Me.OnPropertyChanged("HomePhone")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _HomePhone As String
		Partial Private Sub OnHomePhoneChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnHomePhoneChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property LastName in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property LastName() As String
			Get
				Return Me._LastName
			End Get
			Set(ByVal value As String)
				Me.OnLastNameChanging(value)
				Me._LastName = value
				Me.OnLastNameChanged()
				Me.OnPropertyChanged("LastName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _LastName As String
		Partial Private Sub OnLastNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnLastNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Notes in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Notes() As String
			Get
				Return Me._Notes
			End Get
			Set(ByVal value As String)
				Me.OnNotesChanging(value)
				Me._Notes = value
				Me.OnNotesChanged()
				Me.OnPropertyChanged("Notes")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Notes As String
		Partial Private Sub OnNotesChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnNotesChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Photo in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Photo() As Global.System.Data.Services.Client.DataServiceStreamLink
			Get
				Return Me._Photo
			End Get
			Set(ByVal value As System.Data.Services.Client.DataServiceStreamLink)
				Me.OnPhotoChanging(value)
				Me._Photo = value
				Me.OnPhotoChanged()
				Me.OnPropertyChanged("Photo")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Photo As Global.System.Data.Services.Client.DataServiceStreamLink
		Partial Private Sub OnPhotoChanging(ByVal value As Global.System.Data.Services.Client.DataServiceStreamLink)
		End Sub
		Partial Private Sub OnPhotoChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property PostalCode in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property PostalCode() As String
			Get
				Return Me._PostalCode
			End Get
			Set(ByVal value As String)
				Me.OnPostalCodeChanging(value)
				Me._PostalCode = value
				Me.OnPostalCodeChanged()
				Me.OnPropertyChanged("PostalCode")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _PostalCode As String
		Partial Private Sub OnPostalCodeChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnPostalCodeChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Region in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Region() As String
			Get
				Return Me._Region
			End Get
			Set(ByVal value As String)
				Me.OnRegionChanging(value)
				Me._Region = value
				Me.OnRegionChanged()
				Me.OnPropertyChanged("Region")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Region As String
		Partial Private Sub OnRegionChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnRegionChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ReportsTo in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ReportsTo() As Integer?
			Get
				Return Me._ReportsTo
			End Get
			Set(ByVal value? As Integer)
				Me.OnReportsToChanging(value)
				Me._ReportsTo = value
				Me.OnReportsToChanged()
				Me.OnPropertyChanged("ReportsTo")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ReportsTo? As Integer
		Partial Private Sub OnReportsToChanging(ByVal value? As Integer)
		End Sub
		Partial Private Sub OnReportsToChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Title in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Title() As String
			Get
				Return Me._Title
			End Get
			Set(ByVal value As String)
				Me.OnTitleChanging(value)
				Me._Title = value
				Me.OnTitleChanged()
				Me.OnPropertyChanged("Title")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Title As String
		Partial Private Sub OnTitleChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnTitleChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property TitleOfCourtesy in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property TitleOfCourtesy() As String
			Get
				Return Me._TitleOfCourtesy
			End Get
			Set(ByVal value As String)
				Me.OnTitleOfCourtesyChanging(value)
				Me._TitleOfCourtesy = value
				Me.OnTitleOfCourtesyChanged()
				Me.OnPropertyChanged("TitleOfCourtesy")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _TitleOfCourtesy As String
		Partial Private Sub OnTitleOfCourtesyChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnTitleOfCourtesyChanged()
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
			If (Me.PropertyChangedEvent IsNot Nothing) Then
				RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
			End If
		End Sub
	End Class
	''' <summary>
	''' There are no comments for Northwind.Shippers in the schema.
	''' </summary>
	''' <KeyProperties>
	''' ShipperID
	''' </KeyProperties>
	<Global.System.Data.Services.Common.EntitySetAttribute("Shippers"), Global.System.Data.Services.Common.DataServiceKeyAttribute("ShipperID")> _
	Partial Public Class Shippers
		Implements System.ComponentModel.INotifyPropertyChanged
		''' <summary>
		''' Create a new Shippers object.
		''' </summary>
		''' <param name="shipperID">Initial value of ShipperID.</param>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Shared Function CreateShippers(ByVal shipperID As Integer) As Shippers
			Dim shippers As New Shippers()
			shippers.ShipperID = shipperID
			Return shippers
		End Function
		''' <summary>
		''' There are no comments for Property CompanyName in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property CompanyName() As String
			Get
				Return Me._CompanyName
			End Get
			Set(ByVal value As String)
				Me.OnCompanyNameChanging(value)
				Me._CompanyName = value
				Me.OnCompanyNameChanged()
				Me.OnPropertyChanged("CompanyName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _CompanyName As String
		Partial Private Sub OnCompanyNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCompanyNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Phone in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Phone() As String
			Get
				Return Me._Phone
			End Get
			Set(ByVal value As String)
				Me.OnPhoneChanging(value)
				Me._Phone = value
				Me.OnPhoneChanged()
				Me.OnPropertyChanged("Phone")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Phone As String
		Partial Private Sub OnPhoneChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnPhoneChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipperID in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ShipperID() As Integer
			Get
				Return Me._ShipperID
			End Get
			Set(ByVal value As Integer)
				Me.OnShipperIDChanging(value)
				Me._ShipperID = value
				Me.OnShipperIDChanged()
				Me.OnPropertyChanged("ShipperID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ShipperID As Integer
		Partial Private Sub OnShipperIDChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnShipperIDChanged()
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
			If (Me.PropertyChangedEvent IsNot Nothing) Then
				RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
			End If
		End Sub
	End Class
	''' <summary>
	''' There are no comments for Northwind.Orders in the schema.
	''' </summary>
	''' <KeyProperties>
	''' OrderID
	''' </KeyProperties>
	<Global.System.Data.Services.Common.EntitySetAttribute("Orders"), Global.System.Data.Services.Common.DataServiceKeyAttribute("OrderID")> _
	Partial Public Class Orders
		Implements System.ComponentModel.INotifyPropertyChanged
		''' <summary>
		''' Create a new Orders object.
		''' </summary>
		''' <param name="orderID">Initial value of OrderID.</param>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Shared Function CreateOrders(ByVal orderID As Integer) As Orders
			Dim orders As New Orders()
			orders.OrderID = orderID
			Return orders
		End Function
		''' <summary>
		''' There are no comments for Property Freight in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Freight() As Decimal?
			Get
				Return Me._Freight
			End Get
			Set(ByVal value? As Decimal)
				Me.OnFreightChanging(value)
				Me._Freight = value
				Me.OnFreightChanged()
				Me.OnPropertyChanged("Freight")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Freight? As Decimal
		Partial Private Sub OnFreightChanging(ByVal value? As Decimal)
		End Sub
		Partial Private Sub OnFreightChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property OrderDate in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property OrderDate() As Global.System.DateTime?
			Get
				Return Me._OrderDate
			End Get
			Set(ByVal value? As System.DateTime)
				Me.OnOrderDateChanging(value)
				Me._OrderDate = value
				Me.OnOrderDateChanged()
				Me.OnPropertyChanged("OrderDate")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _OrderDate? As Global.System.DateTime
		Partial Private Sub OnOrderDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnOrderDateChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property OrderID in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property OrderID() As Integer
			Get
				Return Me._OrderID
			End Get
			Set(ByVal value As Integer)
				Me.OnOrderIDChanging(value)
				Me._OrderID = value
				Me.OnOrderIDChanged()
				Me.OnPropertyChanged("OrderID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _OrderID As Integer
		Partial Private Sub OnOrderIDChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnOrderIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property RequiredDate in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property RequiredDate() As Global.System.DateTime?
			Get
				Return Me._RequiredDate
			End Get
			Set(ByVal value? As System.DateTime)
				Me.OnRequiredDateChanging(value)
				Me._RequiredDate = value
				Me.OnRequiredDateChanged()
				Me.OnPropertyChanged("RequiredDate")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _RequiredDate? As Global.System.DateTime
		Partial Private Sub OnRequiredDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnRequiredDateChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipAddress in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ShipAddress() As String
			Get
				Return Me._ShipAddress
			End Get
			Set(ByVal value As String)
				Me.OnShipAddressChanging(value)
				Me._ShipAddress = value
				Me.OnShipAddressChanged()
				Me.OnPropertyChanged("ShipAddress")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ShipAddress As String
		Partial Private Sub OnShipAddressChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipAddressChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipCity in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ShipCity() As String
			Get
				Return Me._ShipCity
			End Get
			Set(ByVal value As String)
				Me.OnShipCityChanging(value)
				Me._ShipCity = value
				Me.OnShipCityChanged()
				Me.OnPropertyChanged("ShipCity")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ShipCity As String
		Partial Private Sub OnShipCityChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipCityChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipCountry in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ShipCountry() As String
			Get
				Return Me._ShipCountry
			End Get
			Set(ByVal value As String)
				Me.OnShipCountryChanging(value)
				Me._ShipCountry = value
				Me.OnShipCountryChanged()
				Me.OnPropertyChanged("ShipCountry")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ShipCountry As String
		Partial Private Sub OnShipCountryChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipCountryChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipName in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ShipName() As String
			Get
				Return Me._ShipName
			End Get
			Set(ByVal value As String)
				Me.OnShipNameChanging(value)
				Me._ShipName = value
				Me.OnShipNameChanged()
				Me.OnPropertyChanged("ShipName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ShipName As String
		Partial Private Sub OnShipNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShippedDate in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ShippedDate() As Global.System.DateTime?
			Get
				Return Me._ShippedDate
			End Get
			Set(ByVal value? As System.DateTime)
				Me.OnShippedDateChanging(value)
				Me._ShippedDate = value
				Me.OnShippedDateChanged()
				Me.OnPropertyChanged("ShippedDate")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ShippedDate? As Global.System.DateTime
		Partial Private Sub OnShippedDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnShippedDateChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipPostalCode in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ShipPostalCode() As String
			Get
				Return Me._ShipPostalCode
			End Get
			Set(ByVal value As String)
				Me.OnShipPostalCodeChanging(value)
				Me._ShipPostalCode = value
				Me.OnShipPostalCodeChanged()
				Me.OnPropertyChanged("ShipPostalCode")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ShipPostalCode As String
		Partial Private Sub OnShipPostalCodeChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipPostalCodeChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipRegion in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ShipRegion() As String
			Get
				Return Me._ShipRegion
			End Get
			Set(ByVal value As String)
				Me.OnShipRegionChanging(value)
				Me._ShipRegion = value
				Me.OnShipRegionChanged()
				Me.OnPropertyChanged("ShipRegion")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ShipRegion As String
		Partial Private Sub OnShipRegionChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipRegionChanged()
		End Sub
		''' <summary>
		''' There are no comments for CustomerID in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property CustomerID() As Customers
			Get
				Return Me._CustomerID
			End Get
			Set(ByVal value As Customers)
				Me._CustomerID = value
				Me.OnPropertyChanged("CustomerID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _CustomerID As Customers
		''' <summary>
		''' There are no comments for EmployeeID in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property EmployeeID() As Employees
			Get
				Return Me._EmployeeID
			End Get
			Set(ByVal value As Employees)
				Me._EmployeeID = value
				Me.OnPropertyChanged("EmployeeID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _EmployeeID As Employees
		''' <summary>
		''' There are no comments for ShipVia in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ShipVia() As Shippers
			Get
				Return Me._ShipVia
			End Get
			Set(ByVal value As Shippers)
				Me._ShipVia = value
				Me.OnPropertyChanged("ShipVia")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ShipVia As Shippers
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
			If (Me.PropertyChangedEvent IsNot Nothing) Then
				RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
			End If
		End Sub
	End Class
	''' <summary>
	''' There are no comments for Northwind.Suppliers in the schema.
	''' </summary>
	''' <KeyProperties>
	''' SupplierID
	''' </KeyProperties>
	<Global.System.Data.Services.Common.EntitySetAttribute("Suppliers"), Global.System.Data.Services.Common.DataServiceKeyAttribute("SupplierID")> _
	Partial Public Class Suppliers
		Implements System.ComponentModel.INotifyPropertyChanged
		''' <summary>
		''' Create a new Suppliers object.
		''' </summary>
		''' <param name="supplierID">Initial value of SupplierID.</param>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Shared Function CreateSuppliers(ByVal supplierID As Integer) As Suppliers
			Dim suppliers As New Suppliers()
			suppliers.SupplierID = supplierID
			Return suppliers
		End Function
		''' <summary>
		''' There are no comments for Property Address in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Address() As String
			Get
				Return Me._Address
			End Get
			Set(ByVal value As String)
				Me.OnAddressChanging(value)
				Me._Address = value
				Me.OnAddressChanged()
				Me.OnPropertyChanged("Address")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Address As String
		Partial Private Sub OnAddressChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnAddressChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property City in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property City() As String
			Get
				Return Me._City
			End Get
			Set(ByVal value As String)
				Me.OnCityChanging(value)
				Me._City = value
				Me.OnCityChanged()
				Me.OnPropertyChanged("City")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _City As String
		Partial Private Sub OnCityChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCityChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property CompanyName in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property CompanyName() As String
			Get
				Return Me._CompanyName
			End Get
			Set(ByVal value As String)
				Me.OnCompanyNameChanging(value)
				Me._CompanyName = value
				Me.OnCompanyNameChanged()
				Me.OnPropertyChanged("CompanyName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _CompanyName As String
		Partial Private Sub OnCompanyNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCompanyNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ContactName in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ContactName() As String
			Get
				Return Me._ContactName
			End Get
			Set(ByVal value As String)
				Me.OnContactNameChanging(value)
				Me._ContactName = value
				Me.OnContactNameChanged()
				Me.OnPropertyChanged("ContactName")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ContactName As String
		Partial Private Sub OnContactNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnContactNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ContactTitle in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ContactTitle() As String
			Get
				Return Me._ContactTitle
			End Get
			Set(ByVal value As String)
				Me.OnContactTitleChanging(value)
				Me._ContactTitle = value
				Me.OnContactTitleChanged()
				Me.OnPropertyChanged("ContactTitle")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ContactTitle As String
		Partial Private Sub OnContactTitleChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnContactTitleChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Country in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Country() As String
			Get
				Return Me._Country
			End Get
			Set(ByVal value As String)
				Me.OnCountryChanging(value)
				Me._Country = value
				Me.OnCountryChanged()
				Me.OnPropertyChanged("Country")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Country As String
		Partial Private Sub OnCountryChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCountryChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Fax in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Fax() As String
			Get
				Return Me._Fax
			End Get
			Set(ByVal value As String)
				Me.OnFaxChanging(value)
				Me._Fax = value
				Me.OnFaxChanged()
				Me.OnPropertyChanged("Fax")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Fax As String
		Partial Private Sub OnFaxChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnFaxChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property HomePage in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property HomePage() As String
			Get
				Return Me._HomePage
			End Get
			Set(ByVal value As String)
				Me.OnHomePageChanging(value)
				Me._HomePage = value
				Me.OnHomePageChanged()
				Me.OnPropertyChanged("HomePage")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _HomePage As String
		Partial Private Sub OnHomePageChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnHomePageChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Phone in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Phone() As String
			Get
				Return Me._Phone
			End Get
			Set(ByVal value As String)
				Me.OnPhoneChanging(value)
				Me._Phone = value
				Me.OnPhoneChanged()
				Me.OnPropertyChanged("Phone")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Phone As String
		Partial Private Sub OnPhoneChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnPhoneChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property PostalCode in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property PostalCode() As String
			Get
				Return Me._PostalCode
			End Get
			Set(ByVal value As String)
				Me.OnPostalCodeChanging(value)
				Me._PostalCode = value
				Me.OnPostalCodeChanged()
				Me.OnPropertyChanged("PostalCode")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _PostalCode As String
		Partial Private Sub OnPostalCodeChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnPostalCodeChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Region in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Region() As String
			Get
				Return Me._Region
			End Get
			Set(ByVal value As String)
				Me.OnRegionChanging(value)
				Me._Region = value
				Me.OnRegionChanged()
				Me.OnPropertyChanged("Region")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Region As String
		Partial Private Sub OnRegionChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnRegionChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property SupplierID in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property SupplierID() As Integer
			Get
				Return Me._SupplierID
			End Get
			Set(ByVal value As Integer)
				Me.OnSupplierIDChanging(value)
				Me._SupplierID = value
				Me.OnSupplierIDChanged()
				Me.OnPropertyChanged("SupplierID")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _SupplierID As Integer
		Partial Private Sub OnSupplierIDChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnSupplierIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Products in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Products() As Global.System.Data.Services.Client.DataServiceCollection(Of Products)
			Get
				Return Me._Products
			End Get
			Set(ByVal value As System.Data.Services.Client.DataServiceCollection(Of Products))
				Me._Products = value
				Me.OnPropertyChanged("Products")
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Products As New Global.System.Data.Services.Client.DataServiceCollection(Of Products)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
			If (Me.PropertyChangedEvent IsNot Nothing) Then
				RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
			End If
		End Sub
	End Class
End Namespace
